(function(){
  if(typeof settings==='undefined'||typeof host==='undefined'||typeof stage==='undefined'||typeof activeLayer!=='function'||typeof makeLayer!=='function')return;
  const KEY='kryvell:nexcreate-suite-v1';
  const state={canvas:{dpi:300,profile:'sRGB',bg:'transparent',symmetry:'off',guides:false},pencil:{curve:100,tilt:0,speed:0,penOnly:false,big:false},transform:{x:0,y:0,scale:100,rotate:0,skewX:0,skewY:0,snap:true},color:{history:[],locked:[]},shape:{type:'round',threshold:128,variant:'balanced'},grain:{type:'paper',intensity:55,scale:32},pack:{name:'ACStudio Brush Pack',brushes:[]}};
  try{const s=JSON.parse(localStorage.getItem(KEY)||'{}');Object.keys(state).forEach(k=>Object.assign(state[k],s[k]||{}))}catch{}
  const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}};
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const dl=(blob,name)=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1800)};
  const saveJSON=(name,obj)=>dl(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),name);
  const canvasBlob=(c,type='image/png',q=.94)=>new Promise(r=>c.toBlob(r,type,q));
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function hexRgb(h){h=String(h||'#000000').replace('#','');if(h.length===3)h=h.split('').map(x=>x+x).join('');const n=parseInt(h,16)||0;return{r:(n>>16)&255,g:(n>>8)&255,b:n&255}}
  function rgbHex(r,g,b){return'#'+[r,g,b].map(v=>clamp(Math.round(v),0,255).toString(16).padStart(2,'0')).join('')}
  function rgbHsl(r,g,b){r/=255;g/=255;b/=255;const mx=Math.max(r,g,b),mn=Math.min(r,g,b),d=mx-mn;let h=0,s=0,l=(mx+mn)/2;if(d){s=d/(1-Math.abs(2*l-1));if(mx===r)h=60*(((g-b)/d)%6);else if(mx===g)h=60*((b-r)/d+2);else h=60*((r-g)/d+4)}return{h:(h+360)%360,s:s*100,l:l*100}}
  function hslHex(h,s,l){h=((h%360)+360)%360;s/=100;l/=100;const c=(1-Math.abs(2*l-1))*s,x=c*(1-Math.abs((h/60)%2-1)),m=l-c/2;let r=0,g=0,b=0;if(h<60){r=c;g=x}else if(h<120){r=x;g=c}else if(h<180){g=c;b=x}else if(h<240){g=x;b=c}else if(h<300){r=x;b=c}else{r=c;b=x}return rgbHex((r+m)*255,(g+m)*255,(b+m)*255)}
  function luminance(hex){const {r,g,b}=hexRgb(hex),f=v=>{v/=255;return v<=.03928?v/12.92:Math.pow((v+.055)/1.055,2.4)};return .2126*f(r)+.7152*f(g)+.0722*f(b)}
  function contrast(a,b){const x=luminance(a),y=luminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05)}

  const side=document.querySelector('.nx-side');if(!side)return;
  const card=document.createElement('section');card.id='nxOmniSuite';card.className='nx-suite-card';card.innerHTML=`<div class="nx-suite-head"><h2>NEXCREATE · Modules complets</h2><span class="nx-suite-badge">OMNI SUITE</span></div><div class="nx-suite-status" id="nxSuiteStatus">Canvas · Pencil · Transform · Colors · Brush Assets · Tattoo · Export actifs en BETA. Pack Procreate = bridge requis.</div><div class="nx-suite-tabs" id="nxSuiteTabs"><button data-tab="canvas">Canvas</button><button data-tab="pencil">Pencil</button><button data-tab="transform">Transform</button><button data-tab="color">Couleurs</button><button data-tab="assets">Brush Assets</button><button data-tab="tattoo">Tattoo</button><button data-tab="export">Export</button><button data-tab="pack">Pack</button></div><div id="nxSuiteBodies"></div>`;
  side.insertBefore(card,side.firstChild||null);
  const bodies=card.querySelector('#nxSuiteBodies');
  const panel=(id,html)=>{const d=document.createElement('div');d.className='nx-suite-tabbody';d.dataset.body=id;d.innerHTML=html;bodies.appendChild(d);return d};
  const pCanvas=panel('canvas',`<div class="nx-suite-head"><h2>Canvas professionnel</h2><span class="nx-suite-badge">DRAW-CANVAS-001</span></div><div class="nx-suite-grid"><label>Largeur px<input id="nxCW" type="number" min="64" max="8192" value="${docW}"></label><label>Hauteur px<input id="nxCH" type="number" min="64" max="8192" value="${docH}"></label><label>DPI<input id="nxDpi" type="number" min="72" max="1200" value="${state.canvas.dpi}"></label><label>Profil<select id="nxProfile"><option>sRGB</option><option>Display-P3</option><option>CMYK-preview</option></select></label><label>Fond<select id="nxBg"><option value="transparent">Transparent</option><option value="white">Blanc</option><option value="charcoal">Charbon</option></select></label><label>Symétrie<select id="nxSym"><option value="off">Off</option><option value="vertical">Verticale</option><option value="horizontal">Horizontale</option><option value="both">Double</option></select></label></div><div class="nx-suite-actions"><button id="nxGuides">Guides</button><button id="nxCreateCanvas">Créer canvas</button></div><div id="nxLayerEstimate" class="nx-suite-summary"></div><p class="nx-suite-note">La limite de calques est une estimation dynamique selon dimensions et mémoire; elle n’est jamais annoncée comme fixe.</p>`);
  const pPencil=panel('pencil',`<div class="nx-suite-head"><h2>Moteur Apple Pencil</h2><span class="nx-suite-badge">DRAW-PENCIL-001</span></div><div class="nx-suite-grid"><label>Courbe pression <output id="nxPOut">${state.pencil.curve}%</output><input id="nxPressureCurve" type="range" min="50" max="250" value="${state.pencil.curve}"></label><label>Inclinaison <output id="nxTOut">${state.pencil.tilt}%</output><input id="nxTilt" type="range" min="0" max="100" value="${state.pencil.tilt}"></label><label>Vitesse <output id="nxSOut">${state.pencil.speed}%</output><input id="nxSpeed" type="range" min="0" max="100" value="${state.pencil.speed}"></label><label>Stabilisation <output id="nxStabOut">${Math.round(settings.stabilizer*100)}%</output><input id="nxStab" type="range" min="0" max="90" value="${Math.round(settings.stabilizer*100)}"></label></div><div class="nx-suite-actions"><button id="nxPenOnly">Stylet seulement: ${state.pencil.penOnly?'ON':'OFF'}</button><button id="nxBigUi">Gros contrôles: ${state.pencil.big?'ON':'OFF'}</button></div><canvas id="nxPencilPad" class="nx-pencil-test"></canvas><p class="nx-suite-note">Palm rejection logiciel: les touches sont ignorées pendant l’usage du stylet. Le comportement Apple Pencil réel dépend du navigateur/appareil.</p>`);
  const pTransform=panel('transform',`<div class="nx-suite-head"><h2>Transformations intelligentes</h2><span class="nx-suite-badge">DRAW-TRANSFORM-001</span></div><div class="nx-suite-grid"><label>X px<input id="nxTX" type="number" value="0"></label><label>Y px<input id="nxTY" type="number" value="0"></label><label>Échelle %<input id="nxTScale" type="number" min="1" max="500" value="100"></label><label>Rotation °<input id="nxTRot" type="number" min="-360" max="360" value="0"></label><label>Distorsion X°<input id="nxTSkewX" type="number" min="-70" max="70" value="0"></label><label>Distorsion Y°<input id="nxTSkewY" type="number" min="-70" max="70" value="0"></label></div><div class="nx-suite-actions"><button id="nxTPreview">Aperçu</button><button id="nxTApply">Appliquer</button><button id="nxTCancel">Annuler aperçu</button><button id="nxTSnap">Snapping: ON</button></div><p class="nx-suite-note">Transformation raster avec historique. Distorsion affine/skew native; perspective/warp projectif exact reste une limite du moteur Canvas 2D actuel.</p>`);
  const pColor=panel('color',`<div class="nx-suite-head"><h2>Couleurs & palettes</h2><span class="nx-suite-badge">DRAW-COLOR-001</span></div><div class="nx-suite-actions"><button id="nxHarmony">Harmonies</button><button id="nxExtract">Extraire canvas</button><button id="nxLockColor">LOCK local couleur</button><button id="nxColorDrop">ColorDrop</button></div><div id="nxPalette" class="nx-palette"></div><div id="nxColorInfo" class="nx-suite-summary"></div><p class="nx-suite-note">Les LOCK ici sont locaux au document et ne remplacent jamais les couleurs canon Airtable. CMYK est affiché comme aperçu mathématique, pas comme épreuve d’impression.</p>`);
  const pAssets=panel('assets',`<div class="nx-suite-head"><h2>Brush Assets</h2><span class="nx-suite-badge">BRUSH-LAB-001 + 002</span></div><div class="nx-suite-grid"><label>Forme<select id="nxShapeType"><option value="round">Ronde</option><option value="square">Carrée</option><option value="diamond">Diamant</option><option value="soft">Douce</option><option value="upload">Image autorisée</option></select></label><label>Seuil<input id="nxShapeThreshold" type="range" min="20" max="235" value="128"></label></div><input id="nxShapeFile" type="file" accept="image/*" hidden><canvas id="nxShapeCanvas" class="nx-suite-preview"></canvas><div class="nx-suite-actions"><button data-shapevariant="soft">Douce</button><button data-shapevariant="balanced">Équilibrée</button><button data-shapevariant="textured">Texturée</button><button id="nxShapeDownload">PNG pointe</button></div><div class="nx-suite-divider"></div><div class="nx-suite-grid"><label>Grain<select id="nxGrainType"><option value="paper">Papier</option><option value="graphite">Graphite</option><option value="charcoal">Charbon</option><option value="ink">Encre</option><option value="stipple">Stippling</option><option value="spray">Spray</option><option value="textile">Textile</option><option value="rnx">RNX</option></select></label><label>Intensité<input id="nxGrainIntensity" type="range" min="5" max="100" value="55"></label></div><canvas id="nxGrainCanvas" class="nx-suite-preview"></canvas><div class="nx-suite-actions"><button id="nxGrainGenerate">Régénérer</button><button id="nxGrainDownload">PNG grain</button></div><p class="nx-suite-note">Formes/grains originaux générés localement. Aucun asset propriétaire de pack commercial n’est extrait.</p>`);
  const pTattoo=panel('tattoo',`<div class="nx-suite-head"><h2>Créateur de crayons tattoo</h2><span class="nx-suite-badge">BRUSH-LAB-004</span></div><div class="nx-suite-actions" id="nxTattooPresets"><button data-tattoo="sketch">Esquisse</button><button data-tattoo="line">Linework</button><button data-tattoo="tribal">Tribal</button><button data-tattoo="black">Blackwork</button><button data-tattoo="whip">Whip shading</button><button data-tattoo="stipple">Stippling</button><button data-tattoo="stencil">Stencil</button><button data-tattoo="fill">Remplissage noir</button></div><button id="nxTattooSheet">Créer planche test</button><p class="nx-suite-note">Simulation numérique uniquement: elle ne prédit pas le comportement réel d’une machine, d’une aiguille ou de la peau.</p>`);
  const pExport=panel('export',`<div class="nx-suite-head"><h2>Export & interopérabilité</h2><span class="nx-suite-badge">DRAW-EXPORT-001</span></div><div class="nx-export-list"><button id="nxExpPng">PNG transparent</button><button id="nxExpBg">PNG avec fond</button><button id="nxExpJpg">JPEG</button><button id="nxExpLayers">Calques PNG</button><button id="nxExpMaster">Document maître JSON</button><button id="nxExpPdf">PDF via Imprimer</button><button disabled>PSD · bridge requis</button><button disabled>TIFF · non garanti navigateur</button></div><p class="nx-suite-note">Le document maître est conservé. Les exports aplatis peuvent perdre calques, masques et modes de fusion; l’interface le signale au lieu de simuler une compatibilité.</p>`);
  const pPack=panel('pack',`<div class="nx-suite-head"><h2>Constructeur de packs</h2><span class="nx-suite-badge bridge">BRUSH-LAB-005 · BRIDGE</span></div><label class="nx-suite-stack">Nom du pack<input id="nxPackName" value="${esc(state.pack.name)}"></label><div class="nx-suite-actions"><button id="nxPackAdd">Ajouter réglage actuel</button><button id="nxPackClear">Vider</button><button class="wide" id="nxPackExport">Exporter manifeste JSON</button></div><div id="nxPackList" class="nx-pack-list"></div><p class="nx-suite-note">Aucun faux .brush/.brushset n’est créé. Le manifeste, les recettes et assets sont préparés; un bridge Procreate réellement testé reste requis pour produire un fichier importable.</p>`);

  function showTab(id){card.querySelectorAll('[data-body]').forEach(x=>x.classList.toggle('active',x.dataset.body===id));card.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));try{localStorage.setItem('kryvell:nx-tab',id)}catch{}}
  card.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));showTab(localStorage.getItem('kryvell:nx-tab')||'canvas');

  stage.style.position=stage.style.position||'relative';const guide=document.createElement('div');guide.className='nx-guide-overlay';stage.appendChild(guide);
  function applyCanvasMeta(){pCanvas.querySelector('#nxProfile').value=state.canvas.profile;pCanvas.querySelector('#nxBg').value=state.canvas.bg;pCanvas.querySelector('#nxSym').value=state.canvas.symmetry;guide.classList.toggle('show',!!state.canvas.guides);host.style.background=state.canvas.bg==='white'?'#fff':state.canvas.bg==='charcoal'?'#222':'transparent';estimateLayers()}
  function estimateLayers(){const w=+pCanvas.querySelector('#nxCW').value||docW,h=+pCanvas.querySelector('#nxCH').value||docH;const mem=(navigator.deviceMemory||4)*1024*1024*1024*.16,per=w*h*4*3;const n=clamp(Math.floor(mem/Math.max(per,1)),1,500);pCanvas.querySelector('#nxLayerEstimate').textContent=`${w} × ${h} · ${pCanvas.querySelector('#nxDpi').value} DPI · ${pCanvas.querySelector('#nxProfile').value} · estimation ≈ ${n} calques selon mémoire disponible.`}
  ['nxCW','nxCH','nxDpi','nxProfile'].forEach(id=>pCanvas.querySelector('#'+id).oninput=estimateLayers);
  pCanvas.querySelector('#nxBg').onchange=e=>{state.canvas.bg=e.target.value;applyCanvasMeta();save()};pCanvas.querySelector('#nxSym').onchange=e=>{state.canvas.symmetry=e.target.value;save()};
  pCanvas.querySelector('#nxGuides').onclick=()=>{state.canvas.guides=!state.canvas.guides;guide.classList.toggle('show',state.canvas.guides);save()};
  pCanvas.querySelector('#nxCreateCanvas').onclick=async()=>{const w=clamp(+pCanvas.querySelector('#nxCW').value||1600,64,8192),h=clamp(+pCanvas.querySelector('#nxCH').value||1600,64,8192);if(!confirm(`Créer le canvas ${w} × ${h} ?`))return;try{await saveDocument()}catch{};state.canvas.dpi=+pCanvas.querySelector('#nxDpi').value||300;state.canvas.profile=pCanvas.querySelector('#nxProfile').value;state.canvas.bg=pCanvas.querySelector('#nxBg').value;resetDocument(w,h);applyCanvasMeta();save()};applyCanvasMeta();

  const symBase=drawSegment;drawSegment=function(a,b){symBase(a,b);const m=state.canvas.symmetry;if(m==='off')return;const pairs=[];if(m==='vertical'||m==='both')pairs.push([{...a,x:docW-a.x},{...b,x:docW-b.x}]);if(m==='horizontal'||m==='both')pairs.push([{...a,y:docH-a.y},{...b,y:docH-b.y}]);if(m==='both')pairs.push([{...a,x:docW-a.x,y:docH-a.y},{...b,x:docW-b.x,y:docH-b.y}]);pairs.forEach(([x,y])=>symBase(x,y))};

  function syncBrushField(name,v){const el=document.querySelector(`[data-brushfield="${name}"]`);if(el){el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}))}}
  pPencil.querySelector('#nxPressureCurve').oninput=e=>{state.pencil.curve=+e.target.value;pPencil.querySelector('#nxPOut').textContent=e.target.value+'%';syncBrushField('pressureCurve',e.target.value);save()};
  pPencil.querySelector('#nxTilt').oninput=e=>{state.pencil.tilt=+e.target.value;pPencil.querySelector('#nxTOut').textContent=e.target.value+'%';syncBrushField('tilt',e.target.value);save()};
  pPencil.querySelector('#nxSpeed').oninput=e=>{state.pencil.speed=+e.target.value;pPencil.querySelector('#nxSOut').textContent=e.target.value+'%';syncBrushField('speed',e.target.value);save()};
  pPencil.querySelector('#nxStab').oninput=e=>{settings.stabilizer=+e.target.value/100;pPencil.querySelector('#nxStabOut').textContent=e.target.value+'%';if(typeof syncControls==='function')syncControls();save()};
  pPencil.querySelector('#nxPenOnly').onclick=e=>{state.pencil.penOnly=!state.pencil.penOnly;e.target.textContent=`Stylet seulement: ${state.pencil.penOnly?'ON':'OFF'}`;save()};
  pPencil.querySelector('#nxBigUi').onclick=e=>{state.pencil.big=!state.pencil.big;document.body.classList.toggle('nx-access-big',state.pencil.big);e.target.textContent=`Gros contrôles: ${state.pencil.big?'ON':'OFF'}`;save()};document.body.classList.toggle('nx-access-big',state.pencil.big);
  let penUntil=0,fillMode=false;host.addEventListener('pointerdown',e=>{if(fillMode){e.preventDefault();e.stopImmediatePropagation();const p=canvasPoint(e);floodFill(Math.round(p.x),Math.round(p.y));fillMode=false;document.getElementById('toolStatus').textContent='ColorDrop appliqué ✅';return}if(e.pointerType==='pen')penUntil=Date.now()+1600;if(e.pointerType==='touch'&&(state.pencil.penOnly||Date.now()<penUntil)){e.preventDefault();e.stopImmediatePropagation()}},true);
  const pad=pPencil.querySelector('#nxPencilPad'),pc=pad.getContext('2d');function sizePad(){pad.width=Math.max(300,pad.clientWidth*devicePixelRatio);pad.height=Math.max(100,pad.clientHeight*devicePixelRatio);pc.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);pc.fillStyle='#111';pc.fillRect(0,0,pad.clientWidth,pad.clientHeight)}sizePad();let pd=false,pp=null;pad.onpointerdown=e=>{pd=true;pp={x:e.offsetX,y:e.offsetY};pad.setPointerCapture?.(e.pointerId)};pad.onpointermove=e=>{if(!pd)return;const p={x:e.offsetX,y:e.offsetY},pr=e.pointerType==='pen'&&e.pressure?e.pressure:.65;pc.strokeStyle=settings.color;pc.lineCap='round';pc.lineWidth=Math.max(1,settings.size*.12*(.3+pr));pc.beginPath();pc.moveTo(pp.x,pp.y);pc.lineTo(p.x,p.y);pc.stroke();pp=p};pad.onpointerup=pad.onpointercancel=()=>{pd=false;pp=null};

  function trVals(){let x=+pTransform.querySelector('#nxTX').value||0,y=+pTransform.querySelector('#nxTY').value||0,r=+pTransform.querySelector('#nxTRot').value||0;if(state.transform.snap){x=Math.round(x/10)*10;y=Math.round(y/10)*10;r=Math.round(r/15)*15}return{x,y,scale:clamp((+pTransform.querySelector('#nxTScale').value||100)/100,.01,5),r,skx:clamp(+pTransform.querySelector('#nxTSkewX').value||0,-70,70),sky:clamp(+pTransform.querySelector('#nxTSkewY').value||0,-70,70)}}
  function previewTransform(){const l=activeLayer();if(!l)return;const v=trVals(),sx=stage.clientWidth/docW,sy=stage.clientHeight/docH;l.canvas.classList.add('nx-transform-preview');l.canvas.style.transformOrigin='50% 50%';l.canvas.style.transform=`translate(${v.x*sx}px,${v.y*sy}px) rotate(${v.r}deg) skew(${v.skx}deg,${v.sky}deg) scale(${v.scale})`}
  function cancelPreview(){layers.forEach(l=>{l.canvas.classList.remove('nx-transform-preview');l.canvas.style.transform=''})}
  pTransform.querySelector('#nxTPreview').onclick=previewTransform;pTransform.querySelector('#nxTCancel').onclick=cancelPreview;pTransform.querySelector('#nxTSnap').onclick=e=>{state.transform.snap=!state.transform.snap;e.target.textContent=`Snapping: ${state.transform.snap?'ON':'OFF'}`;save()};
  pTransform.querySelector('#nxTApply').onclick=()=>{const l=activeLayer();if(!l)return;const v=trVals();cancelPreview();pushHistory();const c=document.createElement('canvas');c.width=docW;c.height=docH;c.getContext('2d').drawImage(l.canvas,0,0);l.ctx.clearRect(0,0,docW,docH);l.ctx.save();l.ctx.translate(docW/2+v.x,docH/2+v.y);l.ctx.rotate(v.r*Math.PI/180);l.ctx.transform(1,Math.tan(v.sky*Math.PI/180),Math.tan(v.skx*Math.PI/180),1,0,0);l.ctx.scale(v.scale,v.scale);l.ctx.drawImage(c,-docW/2,-docH/2);l.ctx.restore();scheduleSave()};

  function setColor(h){settings.color=h;const i=document.getElementById('colorInput');if(i)i.value=h;state.color.history=[h,...state.color.history.filter(x=>x!==h)].slice(0,12);save();renderPalette()}
  document.getElementById('colorInput')?.addEventListener('input',e=>{state.color.history=[e.target.value,...state.color.history.filter(x=>x!==e.target.value)].slice(0,12);save();renderPalette()});
  function currentCmyk(){const {r,g,b}=hexRgb(settings.color),R=r/255,G=g/255,B=b/255,k=1-Math.max(R,G,B);if(k>=.999)return'CMYK 0,0,0,100';return`CMYK ${Math.round((1-R-k)/(1-k)*100)},${Math.round((1-G-k)/(1-k)*100)},${Math.round((1-B-k)/(1-k)*100)},${Math.round(k*100)}`}
  function renderPalette(extra=[]){const colors=[...new Set([settings.color,...extra,...state.color.history])].slice(0,16),box=pColor.querySelector('#nxPalette');box.innerHTML=colors.map(c=>`<button class="nx-swatch ${state.color.locked.includes(c)?'locked':''}" data-c="${c}" style="background:${c}" title="${c}"></button>`).join('');box.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>setColor(b.dataset.c));const cb=contrast(settings.color,'#000000'),cw=contrast(settings.color,'#ffffff');pColor.querySelector('#nxColorInfo').textContent=`${settings.color.toUpperCase()} · ${currentCmyk()} · contraste noir ${cb.toFixed(1)}:1 · blanc ${cw.toFixed(1)}:1 · meilleur texte ${cb>cw?'noir':'blanc'}.`}
  pColor.querySelector('#nxHarmony').onclick=()=>{const {r,g,b}=hexRgb(settings.color),h=rgbHsl(r,g,b),arr=[-60,-30,30,60,120,180].map(d=>hslHex(h.h+d,h.s,h.l));renderPalette(arr)};
  pColor.querySelector('#nxExtract').onclick=()=>{const c=mergeCanvas(),ctx=c.getContext('2d'),freq=new Map(),step=Math.max(4,Math.floor(Math.max(docW,docH)/80));try{const d=ctx.getImageData(0,0,docW,docH).data;for(let y=0;y<docH;y+=step)for(let x=0;x<docW;x+=step){const i=(y*docW+x)*4;if(d[i+3]<80)continue;const q=rgbHex(Math.round(d[i]/32)*32,Math.round(d[i+1]/32)*32,Math.round(d[i+2]/32)*32);freq.set(q,(freq.get(q)||0)+1)}renderPalette([...freq.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).map(x=>x[0]))}catch{renderPalette()}};
  pColor.querySelector('#nxLockColor').onclick=()=>{const c=settings.color,i=state.color.locked.indexOf(c);if(i>=0)state.color.locked.splice(i,1);else state.color.locked.push(c);save();renderPalette()};pColor.querySelector('#nxColorDrop').onclick=()=>{fillMode=true;document.getElementById('toolStatus').textContent='ColorDrop: touche une zone à remplir'};renderPalette();
  function floodFill(x,y){const l=activeLayer();if(!l||l.locked)return;const w=docW,h=docH;if(x<0||y<0||x>=w||y>=h)return;pushHistory();const im=l.ctx.getImageData(0,0,w,h),d=im.data,si=(y*w+x)*4,tr=d[si],tg=d[si+1],tb=d[si+2],ta=d[si+3],nr=hexRgb(settings.color),na=Math.round(settings.opacity*255),tol=28;if(Math.abs(tr-nr.r)+Math.abs(tg-nr.g)+Math.abs(tb-nr.b)+Math.abs(ta-na)<10)return;const q=new Int32Array(w*h),seen=new Uint8Array(w*h);let head=0,tail=0;q[tail++]=y*w+x;const match=idx=>Math.abs(d[idx]-tr)<=tol&&Math.abs(d[idx+1]-tg)<=tol&&Math.abs(d[idx+2]-tb)<=tol&&Math.abs(d[idx+3]-ta)<=tol;while(head<tail){const p=q[head++];if(seen[p])continue;seen[p]=1;const px=p%w,py=(p/w)|0,di=p*4;if(!match(di))continue;d[di]=nr.r;d[di+1]=nr.g;d[di+2]=nr.b;d[di+3]=na;if(px>0)q[tail++]=p-1;if(px<w-1)q[tail++]=p+1;if(py>0)q[tail++]=p-w;if(py<h-1)q[tail++]=p+w;if(tail>=q.length)break}l.ctx.putImageData(im,0,0);scheduleSave()}

  const shapeC=pAssets.querySelector('#nxShapeCanvas'),shapeCtx=shapeC.getContext('2d');shapeC.width=512;shapeC.height=512;let shapeImage=null;
  function renderShape(){const t=pAssets.querySelector('#nxShapeType').value,thr=+pAssets.querySelector('#nxShapeThreshold').value||128,v=state.shape.variant;shapeCtx.clearRect(0,0,512,512);shapeCtx.fillStyle='#fff';shapeCtx.fillRect(0,0,512,512);if(t==='upload'&&shapeImage){const s=Math.min(440/shapeImage.width,440/shapeImage.height),w=shapeImage.width*s,h=shapeImage.height*s;shapeCtx.drawImage(shapeImage,(512-w)/2,(512-h)/2,w,h);const im=shapeCtx.getImageData(0,0,512,512),d=im.data;for(let i=0;i<d.length;i+=4){const g=.299*d[i]+.587*d[i+1]+.114*d[i+2],val=v==='soft'?clamp((g-thr+100)*2,0,255):(g<thr?0:255);d[i]=d[i+1]=d[i+2]=val;d[i+3]=255}shapeCtx.putImageData(im,0,0);return}shapeCtx.save();shapeCtx.translate(256,256);shapeCtx.fillStyle='#000';if(v==='soft'){shapeCtx.shadowColor='#000';shapeCtx.shadowBlur=42}if(t==='square')shapeCtx.fillRect(-150,-150,300,300);else if(t==='diamond'){shapeCtx.rotate(Math.PI/4);shapeCtx.fillRect(-135,-135,270,270)}else{shapeCtx.beginPath();shapeCtx.arc(0,0,t==='soft'?145:155,0,Math.PI*2);shapeCtx.fill()}if(v==='textured'){shapeCtx.globalCompositeOperation='destination-out';for(let i=0;i<800;i++){shapeCtx.globalAlpha=Math.random()*.6;shapeCtx.beginPath();shapeCtx.arc((Math.random()-.5)*280,(Math.random()-.5)*280,Math.random()*3+1,0,Math.PI*2);shapeCtx.fill()}}shapeCtx.restore()}
  pAssets.querySelector('#nxShapeType').onchange=e=>{if(e.target.value==='upload')pAssets.querySelector('#nxShapeFile').click();renderShape()};pAssets.querySelector('#nxShapeThreshold').oninput=renderShape;pAssets.querySelector('#nxShapeFile').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const im=new Image();im.onload=()=>{shapeImage=im;renderShape();URL.revokeObjectURL(im.src)};im.src=URL.createObjectURL(f)};pAssets.querySelectorAll('[data-shapevariant]').forEach(b=>b.onclick=()=>{state.shape.variant=b.dataset.shapevariant;renderShape();save()});pAssets.querySelector('#nxShapeDownload').onclick=async()=>dl(await canvasBlob(shapeC),'NEXCREATE-shape-source.png');renderShape();
  const grainC=pAssets.querySelector('#nxGrainCanvas'),grainCtx=grainC.getContext('2d');grainC.width=512;grainC.height=512;function renderGrain(){const type=pAssets.querySelector('#nxGrainType').value,inten=(+pAssets.querySelector('#nxGrainIntensity').value||55)/100,im=grainCtx.createImageData(512,512),d=im.data,tw=Math.PI*2;for(let y=0;y<512;y++)for(let x=0;x<512;x++){const i=(y*512+x)*4,a=Math.sin(tw*x/64),b=Math.cos(tw*y/64),c=Math.sin(tw*(x+y)/37),e=Math.cos(tw*(x-y)/53);let n=(a+b+c+e)/4;if(type==='graphite')n=.6*n+.4*Math.sin(tw*x/9)*Math.cos(tw*y/13);if(type==='charcoal')n=Math.sign(n)*Math.pow(Math.abs(n),.45);if(type==='ink')n=Math.sin(tw*x/96)*Math.sin(tw*y/96);if(type==='stipple')n=n>.35?1:-.45;if(type==='spray')n=n>.15?Math.sin(tw*x/7)*Math.cos(tw*y/11):-1;if(type==='textile')n=(Math.sin(tw*x/16)+Math.cos(tw*y/16))/2;if(type==='rnx')n=(Math.sin(tw*(x+y)/48)+Math.cos(tw*(x-y)/48)+Math.sin(tw*x/128))/3;const v=clamp(170+n*95*inten,0,255);d[i]=d[i+1]=d[i+2]=v;d[i+3]=255}grainCtx.putImageData(im,0,0)}pAssets.querySelector('#nxGrainType').onchange=renderGrain;pAssets.querySelector('#nxGrainIntensity').oninput=renderGrain;pAssets.querySelector('#nxGrainGenerate').onclick=renderGrain;pAssets.querySelector('#nxGrainDownload').onclick=async()=>dl(await canvasBlob(grainC),'NEXCREATE-grain-seamless.png');renderGrain();

  const tattooPresets={sketch:{size:9,opacity:.55,stab:.3,grain:'charcoal',adv:{spacing:10,jitter:5,taper:20,flow:65}},line:{size:7,opacity:1,stab:.65,grain:'none',adv:{spacing:4,jitter:0,taper:35,flow:100}},tribal:{size:34,opacity:1,stab:.55,grain:'none',adv:{spacing:4,jitter:0,taper:8,flow:100}},black:{size:45,opacity:1,stab:.35,grain:'none',adv:{spacing:4,jitter:0,taper:0,flow:100}},whip:{size:18,opacity:.6,stab:.25,grain:'stipple',adv:{spacing:18,jitter:15,taper:55,flow:65}},stipple:{size:12,opacity:.82,stab:.15,grain:'stipple',adv:{spacing:28,jitter:28,taper:5,flow:80}},stencil:{size:20,opacity:.65,stab:.5,grain:'none',adv:{spacing:6,jitter:0,taper:12,flow:70}},fill:{size:70,opacity:1,stab:.2,grain:'none',adv:{spacing:3,jitter:0,taper:0,flow:100}}};
  function applyTattoo(id){const p=tattooPresets[id];if(!p)return;settings.size=p.size;settings.opacity=p.opacity;settings.stabilizer=p.stab;settings.grain=p.grain;Object.entries(p.adv).forEach(([k,v])=>syncBrushField(k,v));if(typeof syncControls==='function')syncControls();document.getElementById('toolStatus').textContent=`Tattoo preset · ${id}`}
  pTattoo.querySelectorAll('[data-tattoo]').forEach(b=>b.onclick=()=>applyTattoo(b.dataset.tattoo));pTattoo.querySelector('#nxTattooSheet').onclick=()=>{const l=makeLayer('Planche test tattoo'),old={...settings};activeId=l.id;const tests=['line','tribal','whip','stipple','fill'];tests.forEach((id,row)=>{applyTattoo(id);const y=180+row*250;for(let x=160;x<docW-160;x+=26)drawSegment({x,y,p:.35},{x:Math.min(x+26,docW-160),y:y+Math.sin(x/80)*22,p:clamp(.35+(x/docW)*.6,.2,1)})});Object.assign(settings,old);if(typeof syncControls==='function')syncControls();scheduleSave();renderLayers()};

  async function exportMerged(type,bg,name,q=.94){const src=mergeCanvas(),c=document.createElement('canvas');c.width=docW;c.height=docH;const x=c.getContext('2d');if(bg){x.fillStyle=bg;x.fillRect(0,0,docW,docH)}x.drawImage(src,0,0);const b=await canvasBlob(c,type,q);if(b)dl(b,name)}
  pExport.querySelector('#nxExpPng').onclick=()=>exportMerged('image/png',null,'NEXCREATE-transparent.png');pExport.querySelector('#nxExpBg').onclick=()=>exportMerged('image/png',state.canvas.bg==='charcoal'?'#222222':'#ffffff','NEXCREATE-background.png');pExport.querySelector('#nxExpJpg').onclick=()=>exportMerged('image/jpeg','#ffffff','NEXCREATE.jpg',.94);pExport.querySelector('#nxExpLayers').onclick=async()=>{for(let i=0;i<layers.length;i++){const b=await canvasBlob(layers[i].canvas);if(b)dl(b,`NEXCREATE-layer-${String(i+1).padStart(2,'0')}-${layers[i].name.replace(/[^a-z0-9_-]+/gi,'_')}.png`)}};pExport.querySelector('#nxExpMaster').onclick=()=>{const s=snapshot();s.nexcreate={version:'OMNI-SUITE-1',exportedAt:new Date().toISOString(),dpi:state.canvas.dpi,profile:state.canvas.profile,background:state.canvas.bg,symmetry:state.canvas.symmetry,settings:{...settings},warning:'Master JSON preserves raster layer images and metadata available in browser; external proprietary formats are not simulated.'};saveJSON('NEXCREATE-master.json',s)};pExport.querySelector('#nxExpPdf').onclick=()=>{const data=mergeCanvas().toDataURL('image/png'),w=window.open('','_blank');if(!w)return alert('Autorise la fenêtre pour créer le PDF via Imprimer.');w.document.write(`<title>NEXCREATE PDF</title><style>body{margin:0;background:#fff}img{width:100%;height:auto}</style><img src="${data}"><script>setTimeout(()=>print(),500)<\/script>`);w.document.close()};

  function readBrushRecipe(){const fields={};document.querySelectorAll('#brushLab003 [data-brushfield]').forEach(el=>fields[el.dataset.brushfield]=el.type==='range'?Number(el.value):el.value);return{name:`Brush ${state.pack.brushes.length+1}`,addedAt:new Date().toISOString(),core:{size:settings.size,opacity:settings.opacity,stabilizer:settings.stabilizer,color:settings.color,tip:settings.tip,grain:settings.grain},recipe:fields}}
  function renderPack(){state.pack.name=pPack.querySelector('#nxPackName').value;const box=pPack.querySelector('#nxPackList');box.innerHTML=state.pack.brushes.length?state.pack.brushes.map((b,i)=>`<div class="nx-pack-row"><span>${esc(b.name)}</span><button data-rm="${i}">×</button></div>`).join(''):'<div class="nx-suite-mini">Aucun crayon ajouté.</div>';box.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{state.pack.brushes.splice(+b.dataset.rm,1);save();renderPack()});save()}
  pPack.querySelector('#nxPackName').oninput=renderPack;pPack.querySelector('#nxPackAdd').onclick=()=>{state.pack.brushes.push(readBrushRecipe());renderPack()};pPack.querySelector('#nxPackClear').onclick=()=>{state.pack.brushes=[];renderPack()};pPack.querySelector('#nxPackExport').onclick=()=>saveJSON('NEXCREATE-brush-pack-manifest.json',{featureId:'BRUSH-LAB-005',name:state.pack.name,generatedAt:new Date().toISOString(),bridgeRequired:true,formatStatus:'.brush/.brushset/.brushlibrary NOT generated',licenseNote:'Only original/authorized assets should be included.',brushes:state.pack.brushes,assets:{shape:'Export separately from BRUSH-LAB-001',grain:'Export separately from BRUSH-LAB-002'}});renderPack();

  const tested=new Set(['DRAW-OMNI-001','DRAW-SYS-001','DRAW-LAYERS-001','DRAW-SELECT-001','DRAW-ANIM-001']);const native=new Set(['BRUSH-LAB-001','BRUSH-LAB-002','BRUSH-LAB-003','BRUSH-LAB-004','DRAW-CANVAS-001','DRAW-PENCIL-001','DRAW-TRANSFORM-001','DRAW-COLOR-001','DRAW-EXPORT-001']);if(typeof runtimeState==='function'){const old=runtimeState;runtimeState=function(id){if(tested.has(id))return['VALIDÉ','live'];if(native.has(id))return['ACTIF BETA','live'];if(id==='BRUSH-LAB-005')return['BRIDGE REQUIS','bridge'];return old(id)};setTimeout(()=>{try{loadPlanStatus()}catch{}},120)}
})();